package com.projeto_clinicahospitalar.front_end;
import com.projeto_clinicahospitalar.back_end.DadoPessoal;
import com.projeto_clinicahospitalar.back_end.Genero;
import com.projeto_clinicahospitalar.back_end.Endereco;
import com.projeto_clinicahospitalar.back_end.ContatoTelEmail;
import com.projeto_clinicahospitalar.back_end.AtendenteHospitalar;
import com.projeto_clinicahospitalar.back_end.Enfermeiro;
import com.projeto_clinicahospitalar.back_end.ListasDeControle;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

public class TelaCadastroEnfermeiro extends javax.swing.JFrame {
    private JRadioButton radioSim;
    private JRadioButton radioNao;
    private ButtonGroup grupoRaioX;
    /**
     * Creates new form TelaEnfermeiro
     */
    public TelaCadastroEnfermeiro() {
        initComponents();
        this.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        txt_Rua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Celular_CTE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_Telefone_CTE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_DataNascimento = new javax.swing.JTextField();
        txt_Email_CTE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_NomeCompleto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Numero_Endereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Setor = new javax.swing.JTextField();
        txt_CargaHoraria = new javax.swing.JTextField();
        txt_Bairro_Endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Cidade_Endereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botao_LimparDados = new javax.swing.JButton();
        botao_Limpar_Endereco = new javax.swing.JButton();
        botao_Limpar_Contatos = new javax.swing.JButton();
        LimparTodos_Dados = new javax.swing.JButton();
        Registrar_Dados = new javax.swing.JButton();
        Limpar_AtendenteHosp = new javax.swing.JButton();
        txt_Estado_Endereco1 = new javax.swing.JTextField();
        txtCep_Endereco = new javax.swing.JTextField();
        opcao_Genero1 = new javax.swing.JComboBox<>();
        radioRaioXSim = new javax.swing.JRadioButton();
        radioRaioXNao = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        voltarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_Rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_RuaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Data de Nascimento:");

        txt_Celular_CTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Celular_CTEActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nome Completo:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Email:");

        txt_DataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataNascimentoActionPerformed(evt);
            }
        });

        txt_Email_CTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Email_CTEActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Endereço");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Atendente Hospitalar");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Setor:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setText("Carga Horária Semanal:");

        txt_NomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeCompletoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Rua:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Número:");

        txt_Numero_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Numero_EnderecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bairro: ");

        txt_Setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SetorActionPerformed(evt);
            }
        });

        txt_CargaHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CargaHorariaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cidade:");

        txt_Cidade_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cidade_EnderecoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Estado");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Cep:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Cadastro de Enfermeiro");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Contatos");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Celular:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Genero:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Treinado para Raio-X:");

        botao_LimparDados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botao_LimparDados.setText("Limpar Dados");
        botao_LimparDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_LimparDadosActionPerformed(evt);
            }
        });

        botao_Limpar_Endereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botao_Limpar_Endereco.setText("Limpar Endereço");
        botao_Limpar_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_Limpar_EnderecoActionPerformed(evt);
            }
        });

        botao_Limpar_Contatos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botao_Limpar_Contatos.setText("Limpar Contatos");
        botao_Limpar_Contatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_Limpar_ContatosActionPerformed(evt);
            }
        });

        LimparTodos_Dados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LimparTodos_Dados.setText("Limpar Tudo");
        LimparTodos_Dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparTodos_DadosActionPerformed(evt);
            }
        });

        Registrar_Dados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Registrar_Dados.setText("Registrar Dados");
        Registrar_Dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar_DadosActionPerformed(evt);
            }
        });

        Limpar_AtendenteHosp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Limpar_AtendenteHosp.setText("Limpar Antendente Hospitalar");
        Limpar_AtendenteHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpar_AtendenteHospActionPerformed(evt);
            }
        });

        txt_Estado_Endereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estado_Endereco1ActionPerformed(evt);
            }
        });

        txtCep_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCep_EnderecoActionPerformed(evt);
            }
        });

        opcao_Genero1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMININO", "MASCULINO" }));
        opcao_Genero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao_Genero1ActionPerformed(evt);
            }
        });

        radioRaioXSim.setText("Sim");
        radioRaioXSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRaioXSimActionPerformed(evt);
            }
        });

        radioRaioXNao.setText("Não");
        radioRaioXNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRaioXNaoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Dados");

        voltarMenu.setText("Voltar ao Menu Enfermeiro");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Limpar_AtendenteHosp)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel27)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_CargaHoraria, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                        .addComponent(txt_Setor))
                                    .addGap(8, 8, 8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botao_LimparDados)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(radioRaioXSim)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(radioRaioXNao))
                                            .addComponent(txt_DataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_NomeCompleto, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(opcao_Genero1, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(LimparTodos_Dados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Registrar_Dados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(voltarMenu)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botao_Limpar_Endereco)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCep_Endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                        .addComponent(txt_Estado_Endereco1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Cidade_Endereco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Numero_Endereco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Rua, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_Bairro_Endereco, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_Telefone_CTE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(txt_Celular_CTE, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Email_CTE)))
                                    .addComponent(botao_Limpar_Contatos, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(236, 236, 236))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_NomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(opcao_Genero1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioRaioXSim)
                            .addComponent(radioRaioXNao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(botao_LimparDados)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel25)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_Setor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_Celular_CTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txt_Numero_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(txt_Telefone_CTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(txt_Email_CTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Bairro_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1, 1, 1))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_Limpar_Contatos)
                            .addComponent(txt_Cidade_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Estado_Endereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCep_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botao_Limpar_Endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_CargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpar_AtendenteHosp)
                    .addComponent(LimparTodos_Dados)
                    .addComponent(Registrar_Dados)
                    .addComponent(voltarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void txt_RuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_RuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_RuaActionPerformed

    private void txt_Celular_CTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Celular_CTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Celular_CTEActionPerformed

    private void txt_DataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataNascimentoActionPerformed

    private void txt_Email_CTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Email_CTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Email_CTEActionPerformed

    private void txt_NomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeCompletoActionPerformed

    private void txt_Numero_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Numero_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Numero_EnderecoActionPerformed

    private void txt_SetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SetorActionPerformed

    private void botao_Limpar_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_Limpar_EnderecoActionPerformed
        // Limpar dados do endereco
        LimparEndereco();
    }//GEN-LAST:event_botao_Limpar_EnderecoActionPerformed

    private void botao_Limpar_ContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_Limpar_ContatosActionPerformed
        // limpar contatos
        LimparContatos();
    }//GEN-LAST:event_botao_Limpar_ContatosActionPerformed

    private void LimparTodos_DadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparTodos_DadosActionPerformed
        //limpar todos os campos
        LimparDados();
        LimparEndereco();
        LimparContatos();
        LimparAtendHosp();
    }//GEN-LAST:event_LimparTodos_DadosActionPerformed

    private void Registrar_DadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar_DadosActionPerformed
        // TODO add your handling code here:
        try{
            String nome = txt_NomeCompleto.getText().trim();
            String dataNascimento = txt_DataNascimento.getText().trim();
            String genero = (String) opcao_Genero1.getSelectedItem(); 
            boolean treinadoOpRaioX;
            if (radioRaioXSim.isSelected()) {
                treinadoOpRaioX = true;
            } else if (radioRaioXNao.isSelected()) {
                treinadoOpRaioX = false;
            } else {
                throw new IllegalArgumentException("Selecione se foi realizado Raio-X.");
            }

            String rua = txt_Rua.getText().trim();
            String numero = txt_Numero_Endereco.getText().trim();
            String bairro = txt_Bairro_Endereco.getText().trim();
            String cidade = txt_Cidade_Endereco.getText().trim();
            String estado = txt_Estado_Endereco1.getText().trim();
            String cep = txtCep_Endereco.getText().trim();

            String celular = txt_Celular_CTE.getText().trim();
            String telefone = txt_Telefone_CTE.getText().trim();
            String email = txt_Email_CTE.getText().trim();

            String setor = txt_Setor.getText().trim();
            String cargaHora = txt_CargaHoraria.getText().trim();
            
            
            if (radioRaioXSim.isSelected()) {
            } else if (radioRaioXNao.isSelected()) {
            } else {
                throw new IllegalArgumentException("Selecione se foi realizado Raio-X.");
            }


            // Verifica se algum campo está vazio
            if (nome.isEmpty() || dataNascimento.isEmpty()) {
                throw new IllegalArgumentException("Todos os campos dos dados do paciente devem ser preenchidos.");
            }
            if (rua.isEmpty() || numero.isEmpty() || bairro.isEmpty() || cidade.isEmpty() || estado.isEmpty() || cep.isEmpty()) {
                throw new IllegalArgumentException("Todos os campos dos dados do endereço do paciente devem ser preenchidos.");
            }
            if (celular.isEmpty() || telefone.isEmpty() || email.isEmpty()) {
                throw new IllegalArgumentException("Todos os campos dos dados de contato do paciente devem ser preenchidos.");
            }
            if ( !numero.matches("\\d+") || !celular.matches("\\d+") || !telefone.matches("\\d+") || !cargaHora.matches("\\d+")) {
                throw new IllegalArgumentException("Os campos de idade, número, carga horaria, celular e telefone devem conter apenas números.");
            }
            if (!dataNascimento.matches("\\d{2}/\\d{2}/\\d{4}")) {
                throw new IllegalArgumentException("Formato de data inválido. Use dd/MM/yyyy");
            }

            // Verifica se o nome contém apenas letras (regex: [a-zA-ZÀ-ÿ ]+)
            if (!nome.matches("[a-zA-ZÀ-ÿ ]+")) {
                throw new IllegalArgumentException("O nome deve conter apenas letras e espaços.");
            }

            // Conversões
            int numeroEndereco = Integer.parseInt(numero);
            int cepInt = Integer.parseInt(cep);
            long idEnfermeiro = System.currentTimeMillis();
            int cargaHoraria = Integer.parseInt(cargaHora);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date dataNasc = sdf.parse(dataNascimento);
            Date dataCadastro = new Date();

            Endereco endereco = new Endereco(rua, numeroEndereco, bairro, cidade, estado, cepInt);
            Genero generoEnum = Genero.valueOf(genero.toUpperCase());
            ContatoTelEmail contatoEnfermeiro = new ContatoTelEmail(celular, telefone, email);
            
            // Criação do objeto Enfermeiro
            Enfermeiro enfermeiro = new Enfermeiro(
                idEnfermeiro,
                treinadoOpRaioX,
                setor,
                cargaHoraria,
                nome,
                dataNasc,
                endereco,
                generoEnum,
                contatoEnfermeiro                                       
                );
            
            //adicionando enfermeiro no array
            ListasDeControle.ListaEnfermeiro.add(enfermeiro);

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Idade e/ou datas e/ou números devem ser valores numéricos.", "Erro de Entrada", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Erro de Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace(); // aparecer o erro no prompt
            javax.swing.JOptionPane.showMessageDialog(this, "Ocorreu um erro inesperado.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Registrar_DadosActionPerformed

    private void txt_Estado_Endereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estado_Endereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estado_Endereco1ActionPerformed

    private void botao_LimparDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_LimparDadosActionPerformed
        // TODO add your handling code here:
        LimparDados();
    }//GEN-LAST:event_botao_LimparDadosActionPerformed

    private void Limpar_AtendenteHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpar_AtendenteHospActionPerformed
        // TODO add your handling code here:
        LimparAtendHosp();
    }//GEN-LAST:event_Limpar_AtendenteHospActionPerformed

    private void opcao_Genero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao_Genero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcao_Genero1ActionPerformed

    private void radioRaioXSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRaioXSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRaioXSimActionPerformed

    private void radioRaioXNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRaioXNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRaioXNaoActionPerformed

    private void txt_Cidade_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cidade_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cidade_EnderecoActionPerformed

    private void txtCep_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCep_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCep_EnderecoActionPerformed

    private void txt_CargaHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CargaHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CargaHorariaActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        // TODO add your handling code here:
        //limpar todos os campos
        LimparDados();
        LimparEndereco();
        LimparContatos();
        LimparAtendHosp();
        
        //chamar o menu enfermeiro
        MenuEnfermeiro menuEnf = new MenuEnfermeiro();
        menuEnf.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_voltarMenuActionPerformed

    private void LimparContatos(){
        // limpar contatos
        txt_Celular_CTE.setText(" ");
        txt_Telefone_CTE.setText(" ");
        txt_Email_CTE.setText(" ");
    }
    
    private void LimparDados(){
    // Limpar dados: Nome, data nascimento, idade, Genero
        txt_NomeCompleto.setText(" ");
        txt_DataNascimento.setText(" ");
        
    }
   
    private void LimparEndereco(){
        // Limpar dados do endereco
        txt_Rua.setText(" ");
        txt_Numero_Endereco.setText(" ");
        txt_Bairro_Endereco.setText(" ");
        txt_Cidade_Endereco.setText(" ");
        txt_Estado_Endereco1.setText(" ");
        txtCep_Endereco.setText(" ");
    }
    private void LimparAtendHosp(){
        txt_Setor.setText(" ");
        txt_CargaHoraria.setText(" ");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEnfermeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEnfermeiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparTodos_Dados;
    private javax.swing.JButton Limpar_AtendenteHosp;
    private javax.swing.JButton Registrar_Dados;
    private javax.swing.JButton botao_LimparDados;
    private javax.swing.JButton botao_Limpar_Contatos;
    private javax.swing.JButton botao_Limpar_Endereco;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> opcao_Genero1;
    private javax.swing.JRadioButton radioRaioXNao;
    private javax.swing.JRadioButton radioRaioXSim;
    private javax.swing.JTextField txtCep_Endereco;
    private javax.swing.JTextField txt_Bairro_Endereco;
    private javax.swing.JTextField txt_CargaHoraria;
    private javax.swing.JTextField txt_Celular_CTE;
    private javax.swing.JTextField txt_Cidade_Endereco;
    private javax.swing.JTextField txt_DataNascimento;
    private javax.swing.JTextField txt_Email_CTE;
    private javax.swing.JTextField txt_Estado_Endereco1;
    private javax.swing.JTextField txt_NomeCompleto;
    private javax.swing.JTextField txt_Numero_Endereco;
    private javax.swing.JTextField txt_Rua;
    private javax.swing.JTextField txt_Setor;
    private javax.swing.JTextField txt_Telefone_CTE;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables
}
